# © 2017 KAI OS TECHNOLOGIES (HONG KONG) LIMITED, all rights reserved.
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE       := pnscr
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := DATA
LOCAL_SRC_FILES    := pnscr
LOCAL_MODULE_PATH  := $(TARGET_OUT_EXECUTABLES)
include $(BUILD_PREBUILT)

include $(CLEAR_VARS)
LOCAL_MODULE       := Card_Mode.txt
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := DATA
ifeq ($(PRODUCT_MANUFACTURER),SPRD)
LOCAL_SRC_FILES    := Card_Mode_SD.txt
else
LOCAL_SRC_FILES    := Card_Mode.txt
endif

LOCAL_MODULE_PATH  := $(TARGET_OUT_ETC)/nfc
include $(BUILD_PREBUILT)

